### ISSUE TITLE
problem running f_hat

### ISSUE THREAD

**Issue by mlucenaperez** [jacahill/Admixture#3]
Hi James!!

I am trying to use fhat approach to get % of admixture using you code. However, D_stat code is expecting 4 fasta instead of 5, as written in the readme, and hence an error message pop up. Am I suppose to run P1_P2_P3_O and then P1_P2_P4_O? if so, how should I proccedd then with the f_hat.py? 

Thanks,

María.

**Comment by mlucenaperez** [comment]
Solved!! there was a little mistake in the readme. I think that what you meant with the following command in section 3 (fhat):

`**Dstat** P1_all.fa P2_all.fa P3_all.fa P4_all.fa OG_all.fa 5000000 > P1_P2_P3_P4_OG.fhat`

should be instead 

`**Fhat** P1_all.fa P2_all.fa P3_all.fa P4_all.fa OG_all.fa 5000000 > P1_P2_P3_P4_OG.fhat`

isn't it?

**Comment by jacahill** [comment]
Hi Maria,

You're exactly right. It's an error in the readme. 

**Fhat** P1_all.fa P2_all.fa P3_all.fa P4_all.fa OG_all.fa 5000000 > P1_P2_P3_P4_OG.fhat 
is correct.

Thanks!
James
